# Generated by Django 4.2.1 on 2023-05-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contol_estudios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='fecha_nacimiento',
        ),
    ]
