# Generated by Django 4.2.1 on 2023-05-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contol_estudios', '0004_rename_estudiante_socio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Visitante',
        ),
    ]
