# Generated by Django 4.2.1 on 2023-05-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contol_estudios', '0005_rename_profesor_visitante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entregable',
            new_name='Post',
        ),
    ]
